### ISSUE TITLE
The USB set address request failed in debug build

### ISSUE THREAD

**Issue by zgdump** [mvirkkunen/usb-device#80]
Hi!

I used your library in my project for STM32F411CEU and noticed that sometimes Windows shows error 43 in Device Manager. If reconnect device, then everything works as it should

To reproduce the issue, I plugged and popped the device several times. Sometimes it also occurred if leave the stm32 connected via USB and flash using st-link

![image](https://user-images.githubusercontent.com/60278551/147861074-55114e65-fe88-40b9-af4d-00be46e230f1.png)

**Comment by zgdump** [comment]
I am using a Chinese black pill. And everything works fine on firmware, written using C and CubeMX 

![image](https://user-images.githubusercontent.com/60278551/147862064-9127035b-c522-46c1-a0ba-b678ad0bd60c.png)

**Comment by zgdump** [comment]
Hypothetically, i can try to get the dump using a cheap logic analyzer, but I'm not sure that it will be able to work correctly with usb 2.0

**Comment by zgdump** [comment]
I can't figure out what is what and whether my logical analyzer managed to capture data from usb

[RUST USB CDC BUG.zip](https://github.com/mvirkkunen/usb-device/files/7798355/RUST.USB.CDC.BUG.zip)

**Comment by mvirkkunen** [comment]
Can you paste your list of dependencies from `Cargo.toml` with the versions numbers?

**Comment by zgdump** [comment]
My Cargo.toml:

```toml
[package]
name = "motor"
version = "3.0.0"
edition = "2021"

[dependencies]
nb = "1"
cortex-m = "*"
cortex-m-rt = "*"
embedded-hal = "0.2"
usb-device = "0.2.8"
usbd-serial = "0.1.1"
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
arraydeque = { version = "0.4", default-features = false }

[dependencies.stm32f4xx-hal]
version = "0.10"
features = ["stm32f411", "rt", "usb_fs"]
```
